# Project: bingo
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = bingo.o bingo_N.o print_bingo.o
LINKOBJ  = bingo.o bingo_N.o print_bingo.o
LIBS     = -L"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = bingo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

bingo.o: bingo.c
	$(CC) -c bingo.c -o bingo.o $(CFLAGS)

bingo_N.o: bingo_N.c
	$(CC) -c bingo_N.c -o bingo_N.o $(CFLAGS)

print_bingo.o: print_bingo.c
	$(CC) -c print_bingo.c -o print_bingo.o $(CFLAGS)
